stages:
- build
- test
- deploy

image: debian:stable

default:
  before_script:
    - apt update -y
    - apt dist-upgrade -y
    - apt install -y python3-pip git

    - pip3 install --user -U virtualenv pip
    - export PATH=~/.local/bin:$PATH
    
    - virtualenv ~/venv
    - source ~/venv/bin/activate

    - pip install -U pip

    - mkdir -p ~/.pip

# test:
#  script:
#    - python setup.py test
#    - pip install tox flake8  # you can also use tox
#    - tox -e py36,flake8

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
    # an alternative approach is to install and run:
    - pip install dist/*.tar.gz
    # run the command here
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 4 weeks

deploy:
  stage: deploy
  environment: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://git.profinit.eu/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*

# pages:
 # stage: build
 # script:
 #   - pip install sphinx sphinx-rtd-theme
 #   - cd doc ; make html
 #   - mv build/html/ ../public/
 # artifacts:
 #   paths:
 #     - public
 # rules:
 #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

